version: '3.8'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    command: --default-authentication-plugin=mysql_native_password
    
  api:
    image: ghcr.io/tejasvedagiri/stockapi:latest
    # build:
    #   context: ../StockAPI/  
    #   dockerfile: Dockerfile  
    container_name: Eror_Stock_API
    restart: always
    ports:
      - 81:80
    environment:
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOSTNAME: ${MYSQL_HOSTNAME}
      DB_PORT: ${MYSQL_PORT}
      DB_DATABASE: ${MYSQL_DATABASE}
      API_USERNAME: ${API_USERNAME}
      API_PASSWORD: ${API_PASSWORD}
      DB_TYPE: ${DB_TYPE}
  ui:
    image: ghcr.io/tejasvedagiri/stockui:latest
    # build:
    #   context: ../StockUI/  
    #   dockerfile: Dockerfile  
    container_name: Eror_Stock_UI
    restart: always
    ports:
      - 80:80
    environment:
      REACT_APP_API_ENDPOINT: ${REACT_APP_API_ENDPOINT}

