version: '3.8'
services:
  eror_stock_kafka:
    container_name: eror_stock_kafka
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    # volumes:
    #   - "/docker/data/erorstock/kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://eror_stock_kafka:9092 
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@eror_stock_kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  eror_stock_create_topic:
    image: docker.io/bitnami/kafka:3.5
    depends_on:
      - ${KAFKA_HOST}
    entrypoint: /opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server ${KAFKA_HOST}:9092 --replication-factor 1 --partitions 1 --topic stock
  eror_stock_producer:
    container_name: eror_stock_producer
    build:
      context: ./ErorStockProducer/  
      dockerfile: Dockerfile  
    environment:
      KAFKA_CLIENT_USERS: ${KAFKA_CLIENT_USERS}
      KAFKA_CLIENT_PASSWORDS: ${KAFKA_CLIENT_PASSWORDS}
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: 9092
    depends_on:
      - ${KAFKA_HOST}
    ports:
      - 9980:80
  eror_stock_harvester:
    container_name: eror_stock_harvester
    build:
      context: ./ErorStockHarvester/  
      dockerfile: Dockerfile  
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      KAFKA_CLIENT_USERS: ${KAFKA_CLIENT_USERS}
      KAFKA_CLIENT_PASSWORDS: ${KAFKA_CLIENT_PASSWORDS}
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: 9092
    depends_on:
      - ${KAFKA_HOST}
  eror_stock_mysql:
    container_name: eror_stock_mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    command: --default-authentication-plugin=mysql_native_password
    
  # api:
  #   # image: ghcr.io/tejasvedagiri/stockapi:latest
  #   build:
  #     context: ../ErorStockAPIServices/  
  #     dockerfile: Dockerfile  
  #   container_name: Eror_Stock_API
  #   restart: always
  #   ports:
  #     - 81:80
  #   environment:
  #     DB_USERNAME: ${MYSQL_USER}
  #     DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     DB_HOSTNAME: ${MYSQL_HOSTNAME}
  #     DB_PORT: ${MYSQL_PORT}
  #     DB_DATABASE: ${MYSQL_DATABASE}
  #     API_USERNAME: ${API_USERNAME}
  #     API_PASSWORD: ${API_PASSWORD}
  #     DB_TYPE: ${DB_TYPE}
  # ui:
  #   image: ghcr.io/tejasvedagiri/stockui:latest
  #   # build:
  #   #   context: ../StockUI/  
  #   #   dockerfile: Dockerfile  
  #   container_name: Eror_Stock_UI
  #   restart: always
  #   ports:
  #     - 80:80
  #   environment:
  #     REACT_APP_API_ENDPOINT: ${REACT_APP_API_ENDPOINT}

