version: '3.8'
services:
  db:
    container_name: postgre
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 30s
      retries: 5
  api:
    image: ghcr.io/tejasvedagiri/stockapi:latest
    container_name: Eror_Stock_API
    restart: always
    ports:
      - 81:80
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOSTNAME: ${POSTGRES_HOSTNAME}
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}

  ui:
    image: ghcr.io/tejasvedagiri/stockui:latest
    container_name: Eror_Stock_UI
    restart: always
    ports:
      - 80:80

